[package]
name = "watchmen_model"
version = "0.1.0"
edition = "2024"

[dependencies]
bigdecimal = { version = "0.4", features = ["serde"] }
chrono = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
watchmen_model_marco = { path = "../model_marco" }
