[package]
name = "watchmen_runtime_model_kernel"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4"
serde = { version = "1.0", features = ["derive"] }
watchmen_model = { path = "../model" }
