[package]
name = "watchmen_auth"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
watchmen_base = { path = "../base" }
watchmen_model_marco = { path = "../model_marco" }
watchmen_model = {path = "../model" }
