[package]
name = "elf_auth"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.228", features = ["derive"] }
elf_base = { path = "../base" }
elf_model_marco = { path = "../model_marco" }
elf_model = {path = "../model" }
