[package]
name = "watchmen_model_marco"
version = "0.1.0"
edition = "2024"

[lib]
name = "watchmen_model_marco"
path = "src/lib.rs"
proc-macro = true

[dependencies]
quote = "1.0.43"
syn = "2.0.114"
proc-macro2 = "1.0.105"
