[package]
name = "watchmen_model_marco"
version = "0.1.0"
edition = "2024"

[lib]
name = "watchmen_model_marco"
path = "src/lib.rs"
proc-macro = true

[dependencies]
quote = "1.0.41"
syn = "2.0.109"
proc-macro2 = "1.0.103"
lit = "1.0.4"
