[package]
name = "watchmen_base"
version = "0.1.0"
edition = "2024"

[dependencies]
bigdecimal = "0.4"
chrono = "0.4"
serde = { version = "1.0", features = ["derive"] }
config = "0.15"
dotenvy = "0.15"
