[package]
name = "watchmen_base"
version = "0.1.0"
edition = "2024"

[dependencies]
bigdecimal = "0.4.10"
chrono = "0.4.42"
serde = { version = "1.0.228", features = ["derive"] }
config = "0.15.19"
dotenvy = "0.15.7"
